### ISSUE TITLE
error with the test.py

### ISSUE THREAD

**Issue by JammySan** [PSFCPlasmaTools/eqtools#7]
I am jammy  i  have just started with plasma physics and python. I have installed the eqtools in my system and i ran the test.py  for the initial understanding about the tool . but I am getting following error. Please guide me where i am wrong  here.

## --------------------the error -----------------
Warning (from warnings module):
  File "C:\Python\lib\site-packages\eqtools\core.py", line 44
    ModuleWarning)
ModuleWarning: trispline module could not be loaded -- tricubic spline interpolation will not be available.

Warning (from warnings module):
  File "C:\Python\lib\site-packages\eqtools\core.py", line 61
    ModuleWarning)
ModuleWarning: matplotlib modules could not be loaded -- plotting and gfile writing will not be available.

Warning (from warnings module):
  File "C:\Python\lib\site-packages\eqtools\EFIT.py", line 42
    ModuleWarning)
ModuleWarning: MDSplus module could not be loaded -- classes that use MDSplus for data access will not work.

Warning (from warnings module):
  File "C:\Python\lib\site-packages\eqtools\CModEFIT.py", line 42
    ModuleWarning)
ModuleWarning: MDSplus module could not be loaded -- classes that use MDSplus for data access will not work.

Warning (from warnings module):
  File "C:\Python\lib\site-packages\eqtools\NSTXEFIT.py", line 42
    ModuleWarning)
ModuleWarning: MDSplus module could not be loaded -- classes that use MDSplus for data access will not work.

Warning (from warnings module):
  File "C:\Python\lib\site-packages\eqtools\D3DEFIT.py", line 42
    ModuleWarning)
ModuleWarning: MDSplus module could not be loaded -- classes that use MDSplus for data access will not work.

Warning (from warnings module):
  File "C:\Python\lib\site-packages\eqtools\TCVLIUQE.py", line 40
    ModuleWarning)
ModuleWarning: MDSplus module could not be loaded -- classes that use MDSplus for data access will not work.
Traceback (most recent call last):
  File "C:\My_Data\My_Work\MY_NIFS_work\PHD_work\Phd_excersice\Tomo\Tor\tst1.py", line 41, in <module>
    equil.plotFlux(False)
  File "C:\Python\lib\site-packages\SolovievEFIT.py", line 546, in plotFlux
    rGrid = self.getRGrid(length_unit='m')
  File "C:\Python\lib\site-packages\SolovievEFIT.py", line 509, in getRGrid
    unit_factor = self._getLengthConversionFactor(self._defaultUnits['_rGrid'],length_unit)
  File "C:\Python\lib\site-packages\eqtools\core.py", line 8665, in _getLengthConversionFactor
    elif isinstance(start, (int, long)):
NameError: name 'long' is not defined

#-------------------------------------------------------------

looking forward for your guidance.

**Comment by icfaust** [comment]
It seems that you are missing a lot of Software packages on your install of python. That's okay though

A lot of what you have listed are not errors, but warnings, which are handled differently than errors.

The last thing listed is a 'nameError'. Are you running Python 3 on your windows machine? This code was developed in python 2, and hasn't been prepared for that yet.

Let me know.
-Ian

**Comment by JammySan** [comment]
Hello Ian,

Thank you for telling me what is the basic problem which i was facing. Yea
i can see that there is the miss match of the version and thats why the
problem is appearing.

with regards
Shishir
